# Generated by Django 5.2 on 2026-05-20 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Kelajakdagi kasbingizni kuchli IT ustozlar bilan boshlang.', max_length=180)),
                ('subtitle', models.TextField(default='Nova Academy o‘quvchilarni real loyiha asosida tayyorlaydi.')),
                ('hero_badge', models.CharField(default='2026 yil qabuli davom etmoqda', max_length=120)),
                ('students_metric', models.PositiveIntegerField(default=10000)),
                ('teachers_metric', models.PositiveIntegerField(default=28)),
                ('groups_metric', models.PositiveIntegerField(default=86)),
                ('courses_metric', models.PositiveIntegerField(default=12)),
                ('founder_name', models.CharField(default='Maruf Amonturdiyev', max_length=140)),
                ('founder_quote', models.TextField(default='Maqsadimiz yoshlarni xalqaro darajadagi IT mutaxassisga aylantirish.')),
                ('founder_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('grant_text', models.CharField(default='Eng faol o‘quvchilar uchun 30% gacha chegirma va stajirovka tavsiyasi.', max_length=220)),
                ('telegram', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home page sozlamasi',
                'verbose_name_plural': 'Home page sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='FeaturedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('best_student', 'Eng yaxshi o‘quvchi'), ('teacher_of_year', 'Yil o‘qituvchisi'), ('teacher', 'Ustoz')], max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=160)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='featured/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_lessons/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
