# Generated by Django 5.2 on 2026-05-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='application_type',
            field=models.CharField(default='O‘quvchi arizasi', max_length=120),
        ),
    ]
