# Generated by Django 5.2 on 2026-05-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_submission_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student_seen_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
